"""Initial migration

Revision ID: 17732e834e49
Revises: 
Create Date: 2025-07-14 23:28:40.385390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17732e834e49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_bets', sa.Integer(), nullable=True),
    sa.Column('winning_bets', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_games',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('current_score', sa.JSON(), nullable=False),
    sa.Column('game_clock', sa.String(length=20), nullable=True),
    sa.Column('quarter_period', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('idx_live_games_active', 'live_games', ['is_active', 'last_updated'], unique=False)
    op.create_index('idx_live_games_sport', 'live_games', ['sport', 'is_active'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'model_type', 'version', name='uq_model_version')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('odds_data', sa.JSON(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=True),
    sa.Column('away_team', sa.String(), nullable=True),
    sa.Column('commence_time', sa.DateTime(), nullable=True),
    sa.Column('decimal_odds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_odds_bookmaker', 'odds_snapshots', ['bookmaker', 'timestamp'], unique=False)
    op.create_index('idx_odds_game_time', 'odds_snapshots', ['game_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_timestamp'), 'odds_snapshots', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sports', sa.JSON(), nullable=True),
    sa.Column('min_edge', sa.Float(), nullable=True),
    sa.Column('max_kelly_fraction', sa.Float(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('value_bet_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alert_user_created', 'alerts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('kelly_fraction', sa.Float(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('bet_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bet_game', 'bets', ['game_id'], unique=False)
    op.create_index('idx_bet_user_placed', 'bets', ['user_id', 'placed_at'], unique=False)
    op.create_table('live_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('game_clock', sa.String(length=20), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('probability_change', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['live_games.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    timescaledb_hypertable={'time_column_name': 'timestamp'}
    )
    op.create_index('idx_live_events_game_timestamp', 'live_events', ['game_id', 'timestamp'], unique=False)
    op.create_index('idx_live_events_type', 'live_events', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_live_events_timestamp'), 'live_events', ['timestamp'], unique=False)
    op.create_table('live_odds_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('bet_type', sa.String(length=50), nullable=False),
    sa.Column('odds_before', sa.Float(), nullable=True),
    sa.Column('odds_after', sa.Float(), nullable=True),
    sa.Column('line_before', sa.Float(), nullable=True),
    sa.Column('line_after', sa.Float(), nullable=True),
    sa.Column('significance_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['live_games.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    timescaledb_hypertable={'time_column_name': 'timestamp'}
    )
    op.create_index('idx_live_odds_bookmaker_timestamp', 'live_odds_updates', ['bookmaker', 'timestamp'], unique=False)
    op.create_index('idx_live_odds_game_timestamp', 'live_odds_updates', ['game_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_live_odds_updates_timestamp'), 'live_odds_updates', ['timestamp'], unique=False)
    op.create_table('live_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=False),
    sa.Column('away_win_probability', sa.Float(), nullable=False),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['live_games.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    timescaledb_hypertable={'time_column_name': 'prediction_timestamp'}
    )
    op.create_index('idx_live_predictions_game_timestamp', 'live_predictions', ['game_id', 'prediction_timestamp'], unique=False)
    op.create_index('idx_live_predictions_model', 'live_predictions', ['model_version', 'prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_live_predictions_prediction_timestamp'), 'live_predictions', ['prediction_timestamp'], unique=False)
    op.create_table('live_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('subscription_target', sa.String(length=100), nullable=False),
    sa.Column('min_edge_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_subscriptions_type_target', 'live_subscriptions', ['subscription_type', 'subscription_target'], unique=False)
    op.create_index('idx_live_subscriptions_user', 'live_subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_table('live_value_bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('bet_type', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=100), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('fair_odds', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('kelly_fraction', sa.Float(), nullable=True),
    sa.Column('recommended_stake', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['live_games.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    timescaledb_hypertable={'time_column_name': 'detected_at'}
    )
    op.create_index('idx_live_value_bets_active', 'live_value_bets', ['is_active', 'detected_at'], unique=False)
    op.create_index('idx_live_value_bets_edge', 'live_value_bets', ['edge'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_live_value_bets_game', 'live_value_bets', ['game_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_live_value_bets_detected_at'), 'live_value_bets', ['detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_value_bets_detected_at'), table_name='live_value_bets')
    op.drop_index('idx_live_value_bets_game', table_name='live_value_bets')
    op.drop_index('idx_live_value_bets_edge', table_name='live_value_bets', postgresql_where='is_active = true')
    op.drop_index('idx_live_value_bets_active', table_name='live_value_bets')
    op.drop_table('live_value_bets')
    op.drop_index('idx_live_subscriptions_user', table_name='live_subscriptions')
    op.drop_index('idx_live_subscriptions_type_target', table_name='live_subscriptions')
    op.drop_table('live_subscriptions')
    op.drop_index(op.f('ix_live_predictions_prediction_timestamp'), table_name='live_predictions')
    op.drop_index('idx_live_predictions_model', table_name='live_predictions')
    op.drop_index('idx_live_predictions_game_timestamp', table_name='live_predictions')
    op.drop_table('live_predictions')
    op.drop_index(op.f('ix_live_odds_updates_timestamp'), table_name='live_odds_updates')
    op.drop_index('idx_live_odds_game_timestamp', table_name='live_odds_updates')
    op.drop_index('idx_live_odds_bookmaker_timestamp', table_name='live_odds_updates')
    op.drop_table('live_odds_updates')
    op.drop_index(op.f('ix_live_events_timestamp'), table_name='live_events')
    op.drop_index('idx_live_events_type', table_name='live_events')
    op.drop_index('idx_live_events_game_timestamp', table_name='live_events')
    op.drop_table('live_events')
    op.drop_index('idx_bet_user_placed', table_name='bets')
    op.drop_index('idx_bet_game', table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index('idx_alert_user_created', table_name='alerts')
    op.drop_index('idx_alert_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_odds_snapshots_timestamp'), table_name='odds_snapshots')
    op.drop_index('idx_odds_game_time', table_name='odds_snapshots')
    op.drop_index('idx_odds_bookmaker', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('ml_models')
    op.drop_index('idx_live_games_sport', table_name='live_games')
    op.drop_index('idx_live_games_active', table_name='live_games')
    op.drop_table('live_games')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###